### ISSUE TITLE
type definition in function scope not supported

### ISSUE THREAD

**Issue by vejed** [GaijinEntertainment/go-exhaustruct#6] opened 2022-07-21 23:34 UTC
example of go file^
```
package main

import "fmt"

func f1() {
	type args struct {
		n int
	}

	val := args{n: 123}
	fmt.Println(val)
}

func f2() {
	type args struct {
		str string
	}

	val := args{str: "asdf"}
	fmt.Println(val)
}

```

linter output:
```
tst.go:15:7: type `args` is unused (unused)
	type args struct {
	     ^
tst.go:6:7: type `args` is unused (unused)
	type args struct {
	     ^
tst.go:19:9: n is missing in args (exhaustruct)
	val := args{str: "asdf"}
```

**Comment by xobotyi** [comment] 2023-03-04 00:45
Same for me - closing due to inability to reproduce.

**Closed by xobotyi** 2023-03-04 00:45 UTC
Labels: bug
